### ISSUE TITLE
Unexpected first message response

### ISSUE THREAD

**Issue by gregbm99** [atmurray/aiopulse#5]
Logger: aiopulse.hub
Source: __main__.py:347 
First occurred: June 11, 2020, 5:13:54 PM (1 occurrences) 
Last logged: June 11, 2020, 5:13:54 PM

192.168.0.8: First message byte not 0x06

**Comment by atmurray** [comment]
Have you seen this message since the release in Home Assistant?
I improved the way messages were parsed in v0.3.4 that I suspect may have resolved this.
