### ISSUE TITLE
Exception raised when parsing response

### ISSUE THREAD

**Issue by gregbm99** [atmurray/aiopulse#6]
Logger: root
Source: /usr/local/lib/python3.7/site-packages/aiopulse/hub.py:556 
First occurred: June 11, 2020, 5:13:54 PM (1 occurrences) 
Last logged: June 11, 2020, 5:13:54 PM

192.168.0.8: Exception raised when parsing response: b'000000030300009100000003c10100009106536d6172745f4964315f793aaf000101050000000000000010000100060002080038434136040c37280f000100050e000500536576656e0002080037323635040d02110f000100010e00050054687265650002080039364541040d071b0f000100030e000700426564726f6f6d0002080036464432060c2a0d0f0001000a0e000500536f7574680002080036303633060c2c0f0f000100060e0004004561737400020800453034340910290e0f0001000b0e0006004f6666696365ff03'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiopulse/hub.py", line 546, in response_parse
    Hub.respmap[mtype].execute(self, message)
  File "/usr/local/lib/python3.7/site-packages/aiopulse/hub.py", line 468, in execute
    self.function(target, message)
  File "/usr/local/lib/python3.7/site-packages/aiopulse/hub.py", line 496, in rec_message
    raise errors.InvalidResponseException
aiopulse.errors.InvalidResponseException

**Comment by atmurray** [comment]
Fixed in version 0.4.0 where multi-message responses were introduced.
