### ISSUE TITLE
Please add information about hub version support

### ISSUE THREAD

**Issue by nickdos** [atmurray/aiopulse#7]
The Acmeda Pulse hub comes in 2 versions: version 1 (serial connection) and version 2 (network connection). 

Does this library work with both versions, or just version version 1?

FYI, the [Home Assistant integration](https://www.home-assistant.io/integrations/acmeda/) that uses this library, is also lacking this information and the thread below, suggests only version 1 is supported (which is not longer available to buy):

https://community.home-assistant.io/t/rollease-acmeda-automate-pulse-hub-integration/57460/175

**Comment by jcutrell** [comment]
Second this, I have the v2 hub and would be interested in seeing version support information.

**Comment by atmurray** [comment]
Done, have also added a reference to the aiopulse2 project.
