### ISSUE TITLE
Conflicting setup requirement with standard library for Python 3.7 / 3.8

### ISSUE THREAD

**Issue by MartinHjelmare** [atmurray/aiopulse#8]
- This library supports an integration in Home Assistant.
- One or more of the requirements of this library conflicts with one or more standard library modules for Python 3.7 and/or 3.8.
- To avoid issues it would be good if this library would remove these conflicting requirements from your library setup requirements or use a condition to only install the requirements when using a lower Python version.
- If a `setup.py` file is used it means updating the `install_requires` list and removing or updating the conflicting requirements.
  - See this blog for how to use a condition in `install_requires`: https://hynek.me/articles/conditional-python-dependencies/
- Found conflicts:
  - `asyncio`

Thanks for your support of Home Assistant!

**Comment by atmurray** [comment]
Fixed in v0.4.2, I will prepare a pull request for Home Assistant to use this version shortly.
setup.py has been updated as follows:
- Minimum python version 3.4 (python_requires=">=3.4")
- Removed asyncio from install_requires
